# Generated by Django 4.0 on 2021-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_poll_option_1_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_1_counter',
            field=models.IntegerField(default=0, help_text='counter for option 1'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_2_counter',
            field=models.IntegerField(default=0, help_text='counter for option 2'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_3_counter',
            field=models.IntegerField(default=0, help_text='counter for option 3'),
        ),
    ]
